/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloud/worker-configuration.d.ts` (hash: de23325b4f59126112537aeb151e6792)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	KBM_STUDIO_TOKEN: string;
	KBM_GITHUB_TOKEN: string;
	KBM_GITHUB_OWNER: string;
	KBM_GITHUB_REPO: string;
	KBM_GITHUB_REF: string;
	KBM_GITHUB_WORKFLOW: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KBM_STUDIO_TOKEN" | "KBM_GITHUB_TOKEN" | "KBM_GITHUB_OWNER" | "KBM_GITHUB_REPO" | "KBM_GITHUB_REF" | "KBM_GITHUB_WORKFLOW">> {}
}
